### ISSUE TITLE
Documento de especificación de requerimientos

### ISSUE THREAD

**Issue by FedericoVictorianoSierra** [SistemasTecTlaxiaco/actividad-7-documento-de-especificacion-de-requerimientos-equipo-hjfs#1]

**Comment by FedericoVictorianoSierra** [comment]
[Práctica 8 (Federico Victoriano Sierra (5US)).pdf](https://github.com/SistemasTecTlaxiaco/actividad-7-documento-de-especificacion-de-requerimientos-equipo-hjfs/files/10007711/Practica.8.Federico.Victoriano.Sierra.5US.pdf)

**Comment by JoseABCruz** [comment]
[Práctica 8 (José Antonio Balbuena Cruz 5US).pdf](https://github.com/SistemasTecTlaxiaco/actividad-7-documento-de-especificacion-de-requerimientos-equipo-hjfs/files/9902496/Practica.8.Jose.Antonio.Balbuena.Cruz.5US.pdf)

**Comment by Heidi-19** [comment]
[Práctica 8.pdf](https://github.com/SistemasTecTlaxiaco/actividad-7-documento-de-especificacion-de-requerimientos-equipo-hjfs/files/9903402/Practica.8.pdf)

**Comment by SANDRAVELASCO** [comment]
[Práctica 8-2.pdf](https://github.com/SistemasTecTlaxiaco/actividad-7-documento-de-especificacion-de-requerimientos-equipo-hjfs/files/10007809/Practica.8-2.pdf)

**Comment by JoseABCruz** [comment]
[Práctica 8(José Antonio Balbuena Cruz 5US).pdf](https://github.com/SistemasTecTlaxiaco/actividad-7-documento-de-especificacion-de-requerimientos-equipo-hjfs/files/10007805/Practica.8.Jose.Antonio.Balbuena.Cruz.5US.pdf)

**Comment by Heidi-19** [comment]
[Práctica 8 - Heidi Lucy Bautista Sanjuan 5US.pdf](https://github.com/SistemasTecTlaxiaco/actividad-7-documento-de-especificacion-de-requerimientos-equipo-hjfs/files/9956455/Practica.8.-.Heidi.Lucy.Bautista.Sanjuan.5US.pdf)

**Comment by EdwinOrtiz1412** [comment]
calificacion 30

**Comment by Heidi-19** [comment]
[Práctica 8-2.pdf](https://github.com/SistemasTecTlaxiaco/actividad-7-documento-de-especificacion-de-requerimientos-equipo-hjfs/files/10007806/Practica.8-2.pdf)

**Comment by josealfredo79** [comment]
Bien hecho y revisado..Excelente trabajo.
